garden_pip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main_menu.urls', 'main_menu'), namespace='main_menu')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('task_manager/', include(('task_manager.urls', 'task_manager'), namespace='task_manager')),
    path('notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),
    path('sign_in/', include(('sign_in.urls', 'sign_in'), namespace='sign_in')),

]

main_menu/urls.py
# urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_menu, name='main_menu'),
    
    path('get_graph/<str:sensor_name>/', views.get_dynamic_graph, name='get_dynamic_graph'),
    
    path('get_stats/<str:model_name>/', views.get_stats_json, name='get_stats_json'),

    path('get_sensors_config/', views.get_sensors_config, name='get_sensors_config'),
    path('get_alerts_json/', views.get_alerts_json, name='get_alerts_json'),

    path("resolve_alert/<int:alert_id>/", views.resolve_alert, name="resolve_alert"),

    path('resolve_alert/', views.resolve_alert, name='resolve_alert'),  

    path('add_sensor/', views.add_sensor, name='add_sensor'),
]

news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.news, name='news'),
]

notifications/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.notifications, name='notifications'),
]

sign_in/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.sign_in, name='sign_in'),
]

task_manager/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.task_manager, name='task_manager'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="10x10" href="{% static 'img/logo-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'img/logo-icon.png' %}">
    <title>{{ titulo }}</title>
    
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
    <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

	<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&text=air_drop_plant_eco_light_mode_water_drop_dashboard_receipt_long_notifications_login_table_view_verified_user_expand_more" rel="stylesheet" />


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/styles_main_menu.css' %}" />
    <link id="pagestyle" href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />

    <link href="{% static 'css/task.css' %}" rel="stylesheet" />

	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.min.css">
	<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.7.1.js"></script>
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/2.0.8/js/dataTables.min.js"></script>

    <style>
        #miDiv {
            overflow: hidden;
            height: 0;
            transition: height 0.5s ease-in-out;
        }
    </style>
</head>

<body class="g-sidenav-show bg-gray-100">

	<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
	    <div class="container-fluid py-1 px-3">
	        <nav aria-label="breadcrumb">
	            <h6 class="font-weight-bolder mb-0">{{ breadcrumb_titulo|default:'Dashboard' }}</h6>
	        </nav>
	        
	        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
	            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
	                <ul class="navbar-nav justify-content-end">
	                    <li class="nav-item d-flex align-items-center me-3">
	                        <span class="text-dark text-sm me-2">Última actualización:</span>
	                        <span class="text-dark font-weight-bold text-sm">{{ last_update_time|date:"H:i:s" }}</span>
	                    </li>
	                    <li class="nav-item d-flex align-items-center position-relative">
	                        <a href="{% url 'notifications:notifications' %}" class="nav-link text-body p-0">
	                            <i class="fa fa-bell cursor-pointer me-2" 
	                               {% if active_alerts_count > 0 %} style="color: #ff5252;" {% else %} style="color: #ffffff;" {% endif %}></i>
	                        </a>
	                        {% if active_alerts_count > 0 %}
	                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
	                                {{ active_alerts_count }}
	                                <span class="visually-hidden">Alertas activas</span>
	                            </span>
	                        {% endif %}
	                    </li>
	                </ul>
	            </div>
	            
	            <ul class="navbar-nav justify-content-end">
	                <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
	                    <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
	                        <div class="sidenav-toggler-inner">
	                            <i class="sidenav-toggler-line"></i>
	                            <i class="sidenav-toggler-line"></i>
	                            <i class="sidenav-toggler-line"></i>
	                        </div>
	                    </a>
	                </li>
	            </ul>
	        </div>
	    </div>
	</nav>

    <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark" id="sidenav-main">
        <div class="sidenav-header">
            <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
            <a class="navbar-brand m-0" href="" target="_blank">
                <img src="{% static '/img/logo.png' %}" class="navbar-brand-img" alt="main_logo">
                <span class="ms-1 font-weight-bold text-white">{{ titulo }}</span>
            </a>
        </div>
        <hr class="horizontal light mt-0 mb-2">
        <div class="collapse navbar-collapse w-auto" id="sidenav-collapse-main">
            <ul class="navbar-nav">
                <li class="nav-item mt-3">
                    <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Menú principal</h6>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'main_menu:main_menu' %}">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-symbols-rounded opacity-10">dashboard</i>
                        </div>
                        <span class="nav-link-text ms-1">{{ app_1 }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'news:news' %}">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-symbols-rounded opacity-10">table_view</i>
                        </div>
                        <span class="nav-link-text ms-1">{{ app_2 }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'task_manager:task_manager' %}">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-symbols-rounded opacity-10">receipt_long</i>
                        </div>
                        <span class="nav-link-text ms-1">{{ app_3 }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'notifications:notifications' %}">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-symbols-rounded opacity-10">notifications</i>
                        </div>
                        <span class="nav-link-text ms-1">{{ app_4 }}</span>
                    </a>
                </li>
                
                <li class="nav-item mt-3">
                    <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Agrónomo</h6>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'sign_in:sign_in' %}">
                        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="material-symbols-rounded opacity-10">login</i>
                        </div>
                        <span class="nav-link-text ms-1">{{ app_5 }}</span>
                    </a>
                </li>
            </ul>
        </div>
    </aside>


    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.4.1/echarts.min.js"></script>
    <script>
        // Lógica de Scrollbar (si se aplica)
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
    
    <script>
        var boton = document.getElementById('miBoton');
        var miDiv = document.getElementById('miDiv');
        
        boton.addEventListener('click', function () {
            if (miDiv.style.height === '0px' || miDiv.style.height === '') {
                miDiv.style.height = '50px';
                miDiv.textContent = 'Será esencial realizar un análisis del suelo y ajustar el aporte de nutrientes para garantizar un crecimiento saludable y una cosecha abundante en el futuro. No descuidar los niveles de humedad';
            } else {
                miDiv.style.height = '0';
                miDiv.textContent = '';
            }
        });
    </script>

	<script async defer src="https://buttons.github.io/buttons.js"></script>
    <script src="{% static 'js/material-dashboard.min.js' %}"></script>
</body>
</html>

templates/topbar.html
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
    <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
            <h6 class="font-weight-bolder mb-0">{{ breadcrumb_titulo|default:'Dashboard' }}</h6>
        </nav>
        
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item d-flex align-items-center me-3">
                        <span class="text-white text-sm me-2">Última actualización:</span>
                        <span class="text-white font-weight-bold text-sm">{{ last_update_time|date:"H:i:s" }}</span>
                    </li>
                    <li class="nav-item d-flex align-items-center position-relative">
                        <a href="{% url 'notifications:notifications' %}" class="nav-link text-body p-0">
                            <i class="fa fa-bell cursor-pointer me-2" 
                               {% if active_alerts_count > 0 %} style="color: #ff5252;" {% else %} style="color: #ffffff;" {% endif %}></i>
                        </a>
                        {% if active_alerts_count > 0 %}
                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                {{ active_alerts_count }}
                                <span class="visually-hidden">Alertas activas</span>
                            </span>
                        {% endif %}
                    </li>
                </ul>
            </div>
            
            <ul class="navbar-nav justify-content-end">
                <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>